"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/component/Navbar";
import {store} from "@/redux/store";
import { Provider } from 'react-redux'
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// store
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <Provider store={store} >
    <html lang="en">
      <body className={inter.className}>

      {children}</body>
    </html>
      </Provider>
  )
}
